### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by evilester** [devsapp/fc-core#14]
bug
s deploy
![image](https://user-images.githubusercontent.com/4954490/158972164-bb70ceda-6be1-49fb-8a43-fa2221d2b888.png)

![image](https://user-images.githubusercontent.com/4954490/158971846-815567ca-9c76-438b-ac5e-1755180d27f6.png)
![image](https://user-images.githubusercontent.com/4954490/158972004-0891e7cb-fb32-458f-b87f-379be159006a.png)

**Comment by heimanba** [comment]
麻烦请问下是时候什么模版哈？
